name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Trigger App Runner deployment
        run: |
          SERVICE_ARN=$(aws apprunner list-services --region us-west-2 --query "ServiceSummaryList[?ServiceName=='smartceo-remote-mcp'].ServiceArn" --output text)

          if [ -z "$SERVICE_ARN" ]; then
            echo "❌ Service not found"
            exit 1
          fi

          echo "🚀 Triggering deployment for service: $SERVICE_ARN"
          aws apprunner start-deployment --service-arn "$SERVICE_ARN" --region us-west-2

          echo "✅ Deployment triggered successfully"
          echo "⏳ Deployment will take 3-5 minutes"
